# Generated by Django 4.2.1 on 2023-05-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_and_update_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetprice',
            name='symbol',
            field=models.CharField(),
        ),
    ]
