# Generated by Django 4.2.1 on 2023-05-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_and_update_data', '0002_alter_assetprice_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='B3Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField()),
                ('minutes_update_rate', models.IntegerField()),
                ('run', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'b3_companies',
                'unique_together': {('symbol', 'run')},
            },
        ),
    ]
