# Generated by Django 4.2.1 on 2023-06-03 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_and_update_data', '0003_b3companies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='B3Companies',
            new_name='B3Companie',
        ),
    ]
