# Generated by Django 4.2.1 on 2023-06-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_and_update_data', '0005_stockportfolio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockportfolio',
            unique_together={('symbol', 'date', 'username')},
        ),
        migrations.AlterModelTable(
            name='stockportfolio',
            table='stock_prices',
        ),
    ]
