# Generated by Django 4.2.1 on 2023-06-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_and_update_data', '0006_alter_stockportfolio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockportfolio',
            table='users_stocks',
        ),
    ]
