# Generated by Django 4.2.1 on 2023-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_and_update_data', '0008_alter_stockportfolio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockportfolio',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='stockportfolio',
            unique_together={('symbol', 'date', 'username')},
        ),
    ]
