# Generated by Django 4.2.1 on 2023-06-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_and_update_data', '0010_alter_stockportfolio_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assetprice',
            name='granularity',
            field=models.CharField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='assetprice',
            unique_together={('symbol', 'datetime', 'granularity')},
        ),
    ]
