# Generated by Django 4.2.1 on 2023-06-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_and_update_data', '0018_remove_stockportfolio_sold_stockportfolio_sold_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetprice',
            name='granularity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assetprice',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
