# Generated by Django 4.2.1 on 2023-06-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_and_update_data', '0019_alter_assetprice_granularity_alter_assetprice_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
            ],
            options={
                'unique_together': {('date_received', 'email', 'type')},
            },
        ),
    ]
